name: release

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  
jobs:
  build-publish-release:
    name: "release"
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: write
      packages: write
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Setup buildx instance
        uses: docker/setup-buildx-action@v1
        with:
          use: true

      - uses: actions/cache@v2
        with:
          key: ${{ runner.OS }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build

      - name: Log in to the GHCR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: anchore/sbom-action/download-syft@v0.5.0
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --timeout 30m --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
