name: release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  REGISTRY: ghcr.io

jobs:
  build-publish-release:
    name: "release"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Setup buildx instance
        uses: docker/setup-buildx-action@v1
        with:
          use: true

      - uses: actions/cache@v2
        with:
          key: ${{ runner.OS }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
      - uses: crazy-max/ghaction-github-runtime@v1

      # need to convert repo name to lowercase for Docker
      - name: Get tag and repo
        run: |
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "REPO=$(echo $GITHUB_REPOSITORY | awk '{print tolower($0)}')" >> $GITHUB_ENV

      - name: print vars
        run: |
          echo $REPO
          echo $TAG

      - name: Build eraser-manager
        run: make docker-build-manager \
          OUTPUT_TYPE=type=docker \
          CACHE_FROM=type=gha,scope=eraser-manager \
          CACHE_TO=type=gha,scope=eraser-manager,mode=max \
          MANAGER_IMG=${{ env.REGISTRY }}/${REPO}-manager:${TAG}

      - name: Build eraser
        run: make docker-build-eraser \
          OUTPUT_TYPE=type=docker \
          CACHE_FROM=type=gha,scope=eraser-node \
          CACHE_TO=type=gha,scope=eraser-node,mode=max \
          ERASER_IMG=${{ env.REGISTRY }}/${REPO}:${TAG}

      - name: Log in to the GHCR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        run: |
          make docker-push-manager MANAGER_IMG=${{ env.REGISTRY }}/${REPO}-manager:${TAG}
          make docker-push-eraser ERASER_IMG=${{ env.REGISTRY }}/${REPO}:${TAG}

      - name: Create GitHub release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
