name: test
on:
  push:
    paths-ignore:
      - "**.md"
      - "hack/**"
  pull_request:
    paths-ignore:
      - "**.md"
      - "hack/**"

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  test:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/cache@v2
        with:
          key: ${{ runner.OS }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Unit test
        run: make test

  e2e:
    name: "End to End Test"
    env:
      CLUSTER_NAME: e2e-cluster
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Setup buildx instance
        uses: docker/setup-buildx-action@v1
        with:
          use: true

      - uses: actions/cache@v2
        with:
          key: ${{ runner.OS }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build

      - uses: crazy-max/ghaction-github-runtime@v1

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          config: .github/workflows/kind-config/kind-config.yaml

      - name: Build controller
        run: make docker-build CACHE_FROM=type=gha,scope=eraser-manager CACHE_TO=type=gha,scope=eraser-manager,mode=max IMG=ghcr.io/azure/eraser-manager:test

      - name: Build eraser
        run: make docker-build-eraser CACHE_FROM=type=gha,scope=eraser-node CACHE_TO=type=gha,scope=eraser-node,mode=max ERASER_IMG=ghcr.io/azure/eraser:test

      - name: Generate manifests
        run: make generate manifests

      - name: Deploy images
        run: make deploy IS_IC=true ERASER_IMG=ghcr.io/azure/eraser:test

      - name: Pull test image
        run: docker pull hello-world

      - name: Load controller and eraser image on the nodes of the cluster
        run: |
          kind load docker-image ghcr.io/azure/eraser-manager:test ghcr.io/azure/eraser:test hello-world:latest --name ${{ env.CLUSTER_NAME }}

      - name: Sleep for 10 seconds
        run: sleep 10s

      - name: Get list of images from control-plane node
        run: docker exec ${{ env.CLUSTER_NAME }}-control-plane ctr -n k8s.io images list

      - name: Deploy eraser_e2e_imagelist.yaml
        run: kubectl apply -f config/samples/eraser_e2e_imagelist.yaml

      - name: Sleep for 10 seconds
        run: sleep 10s

      - name: Get image list
        run: kubectl get imagelist

      - name: Sleep for 10 seconds
        run: sleep 10s

      - name: Get image job
        run: kubectl get imagejob

      - name: Get pods
        run: kubectl get pod -A

      - name: Sleep for 10 seconds
        run: sleep 10s

      - name: Check if pods are scheduled on all nodes
        run: |
          chmod u+x .github/workflows/e2e-scripts/checkifpodfitnode.sh
          ./.github/workflows/e2e-scripts/checkifpodfitnode.sh ${{ env.CLUSTER_NAME }}

      - name: Check if pods are complete.
        run: |
          chmod u+x .github/workflows/e2e-scripts/checkifpodsarecomplete.sh
          ./.github/workflows/e2e-scripts/checkifpodsarecomplete.sh ${{ env.CLUSTER_NAME }}

      - name: Check if test image is removed
        run: |
          chmod u+x .github/workflows/e2e-scripts/checktestimagewasremoved.sh
          ./.github/workflows/e2e-scripts/checktestimagewasremoved.sh ${{ env.CLUSTER_NAME }}
